[ids]

*

[main]

# Map capslock to capslock when pressed and shift when held.
capslock = overload(shift, capslock)


# Maps space to a custom layer, but just "space" when pressed.
space = overload(space, space)

# Space layer
[space]

## Arrows
i = up
j = left
k = down
l = right

## Fast-nav
u = C-left
o = C-right
y = pageup
h = pagedown
m = home
. = end

## Deletion
p = C-backspace
; = backspace


